// Check the buyer/router account's WCSPR balance via CSPR.cloud (testnet).
//
//   node scripts/check-wcspr.mjs
//
import { config } from "../server/config.js";
import fs from "node:fs";
import path from "node:path";
import sdk from "casper-js-sdk";

const { PublicKey } = sdk;

const pkg = config.x402.asset;
const decimals = Number(config.x402.assetExtra.decimals);

// Read the buyer public key generated by scripts/generate-key.mjs.
const pubHexPath = path.join(process.cwd(), "keys", "public_key_hex");
if (!fs.existsSync(pubHexPath)) {
  console.error("keys/public_key_hex not found. Run: node scripts/generate-key.mjs");
  process.exit(1);
}
const pubHex = fs.readFileSync(pubHexPath, "utf8").trim();
const accountHash = PublicKey.fromHex(pubHex).accountHash().toHex().replace(/^account-hash-/, "");

const url = `https://api.testnet.cspr.cloud/accounts/${accountHash}/ft-token-ownership?contract_package_hash=${pkg}`;
const res = await fetch(url, { headers: { accept: "application/json", authorization: config.x402.accessToken } });
const json = await res.json();

const row = json.data?.[0];
const raw = row ? BigInt(row.balance) : 0n;
const human = Number(raw) / 10 ** decimals;

console.log("Account hash:", accountHash);
console.log("WCSPR balance (raw):", raw.toString());
console.log(`WCSPR balance:       ${human} WCSPR`);
if (raw === 0n) {
  console.log("\n=> 0 WCSPR. Wrap some CSPR at https://testnet.cspr.trade (swap CSPR -> Wrapped CSPR) with this account.");
} else {
  console.log("\n=> You hold WCSPR. Ready to run a real x402 settlement via /api/run.");
}
